config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'attendances#index'

  resources :attendances

  resource :profile, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
# == Schema Information
#
# Table name: attendances
#
#  id         :bigint           not null, primary key
#  break_time :integer
#  content    :text
#  end_time   :datetime
#  start_time :datetime         not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_attendances_on_user_id  (user_id)
#
class Attendance < ApplicationRecord
  has_one_attached :eyecatch

  validates :start_time, presence: true

  belongs_to :user

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def display_start_time
    I18n.l(self.start_time, format: :long)
  end

  def display_end_time
    return '----/--/-- --:--' unless end_time.present?
    I18n.l(self.end_time, format: :long)
  end

  def author_name
    user.display_name
  end
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :bigint           not null, primary key
#  birthday   :date
#  job        :integer
#  nickname   :string
#  subscribed :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  enum job: { teacher: 0, officeworker: 1, parttime: 2 }
  belongs_to :user
  has_one_attached :avatar

  def age
    return '不明' unless birthday.present?
    years = Time.zone.now.year - birthday.year
    days = Time.zone.now.yday - birthday.yday

    if days < 0
      "#{years - 1}歳"
    else
      "#{years}歳"
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :attendances, dependent: :destroy
  has_one :profile, dependent: :destroy


  delegate :birthday, :age, :job, to: :profile, allow_nil: true

  def has_written?(attendance)
    attendances.exists?(id: attendance.id)
  end

  def display_name
    profile&.nickname || self.email.split('@').first
  end

  def prepare_profile
    profile || build_profile
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show]
  before_action :authenticate_user!
  def index
    @attendances = Attendance.all
  end

  def show
  end

  def new
    @attendance = current_user.attendances.build
  end

  def create
    @attendance = current_user.attendances.build(attendance_params)
    if @attendance.save
      redirect_to attendance_path(@attendance), notice: '保存しました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    @attendance = current_user.attendances.find(params[:id])
  end

  def update
    @attendance = current_user.attendances.find(params[:id])
    if @attendance.update(attendance_params)
      redirect_to attendance_path(@attendance), notice: '更新しました'
    else
      flash.now[:error] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    attendance = current_user.attendances.find(params[:id])
    attendance.destroy!
    redirect_to root_path, notice: '削除しました'
  end

  private
  def attendance_params
    params.require(:attendance).permit(
      :start_time,
      :end_time,
      :break_time,
      :content,
      :eyecatch
    )
  end

  def set_attendance
    @attendance = Attendance.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィールを更新しました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :nickname,
      :job,
      :birthday,
      :subscribed,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attendances/_form.html.haml
.container
  %ul
    - attendance.errors.full_messages.each do |message|
      %li= message
  = form_with(model: attendance, local: true) do |f|
    %div
      = f.label :start_time, '出勤時間'
    %div
      = f.time_field :start_time, class: 'text'
    %div
      = f.label :end_time, '退勤時間'
    %div
      = f.time_field :end_time, class: 'text'
    %div
      = f.label :break_time, '休憩時間(時間)'
    %div
      = f.number_field :break_time, class: 'text'
    %div
      = f.label :content, '補足内容'
    %div
      = f.label :eyecatch, '写真を追加する'
    %div
      = f.file_field :eyecatch
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/attendances/_tabs.html.haml
.tabs
  .tabs_item.active
    出退勤者一覧

app/views/attendances/edit.html.haml
= render 'form', attendance: @attendance

app/views/attendances/index.html.haml
.container
  = render 'tabs'
  - @attendances.each do |attendance|
    = render 'commons/attendance', attendance: attendance
  = link_to new_attendance_path do
    .float_btn
      %p 出退勤を入力する

app/views/attendances/new.html.haml
= render 'form', attendance: @attendance

app/views/attendances/show.html.haml
.attendance
  .attendance_detail
    = image_tag @attendance.user.avatar_image
    %div
      %p= @attendance.author_name
      %p= @attendance.display_created_at
    - if user_signed_in? && current_user.has_written?(@attendance)
      .attendance_detail_actions
        .dropdown
          = image_tag 'actions.svg', class: 'dropbtn'
          .dropdown-content.mini
            = link_to'編集する', edit_attendance_path(@attendance)
            = link_to'削除する', attendance_path(@attendance), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
  .attendance_start_time
    .attendance_title
      %p 出勤時間
    .attendance_time= @attendance.display_start_time
  .attendance_end_time
    .attendance_title
      %p 退勤時間
    .attendance_time= @attendance.display_end_time
  .attendance_break_time
    .attendance_title
      %p 休憩時間
    = "#{@attendance.break_time}時間"
  .attendance_content
    .attendance_title
      %p 補足コメント
    = @attendance.content
  .attendance_photo
    .attendance_title
      %p 写真
      - if @attendance.eyecatch.attached?
        .attendance_image
          = image_tag @attendance.eyecatch

app/views/commons/_attendance.html.haml
= link_to attendance_path(attendance) do
  .card
    .card_content
      .card_title
        %p 入力日
        %p= attendance.display_created_at
      .card_detail
        = image_tag attendance.user.avatar_image
        %div
          %p= attendance.author_name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AttendanceApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %link{:href => "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  %body
    %header.header
      .header_logos
        - if !current_page?(root_path)
          = link_to :back do
            = image_tag 'back.svg', class: 'header_back'
        %p.header_pageTitle
          = link_to '勤怠App', root_path
      - if user_signed_in?
        .dropdown
          = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'プロフィール', profile_path
            = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }
      - else
        = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/profiles/edit.html.haml
.container
  %ul
    - @profile.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div
      = f.label :avatar, 'アバター'
    %div
      = f.file_field :avatar
    %div
      = f.label :nickname, '氏名'
    %div
      = f.text_field :nickname, class: 'text'
    %div
      = f.label :job, '職種'
    %div
      = f.select :job, Profile.jobs.map { |k, v| [ I18n.t("enum.jobs.#{k}"), k ] }, {}, { class: 'text' }
    %div
      = f.label :birthday, '生年月日'
    %div
      = f.date_field :birthday, class: 'text'
    %div
      = f.label :subscribed, '通知を受け取る'
      = f.check_box :subscribed

    = f.submit '保存', class: 'btn-primary'

app/views/profiles/show.html.haml
.container.profilePage
  .profilePage_user
    .profilePage_user_image
      = image_tag current_user.avatar_image
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          #{current_user.display_name}（#{current_user.age || '?歳'}・#{I18n.t("enum.jobs.#{current_user.job || 'unknown'}")}）
        .profilePage_user_actionButton
          = link_to 'Edit', edit_profile_path

  .tabs
    .tabs_item.active
      私の出退勤日一覧
  - current_user.attendances.each do |attendance|
    = render 'commons/attendance', attendance: attendance